version: "3"

services:
  app:
    user: $UID:$GID
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
    environment:
      - DB_HOST=db
      - DB_NAME=app
      - DB_USER=postgres
      - DB_PASS=strongpassword
    command: >
      sh -c " python manage.py migrate &&
              python manage.py runserver 0.0.0.0:8000"

    depends_on:
      - db

  db:
    image: postgres:10-alpine
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_DB=app
      - POSTGRES_USER=postgres
      - POSTGRES_PASS=strongpassword
